weights:
  # Forward growth total = 30
  growth_revenue: 20
  growth_netincome: 10

  upside: 20

  # Recommendations total = 20
  recs_level: 10
  recs_momentum: 10

  revisions: 15
  surprises: 10
  dispersion: 3
  coverage: 2

gates:
  cap_eps_le_zero: 60     # legacy keys ok to keep
  cap_eps_le_zero_lowrev: 50
  rev_growth_low_threshold_pct: 10

freshness:
  estimates_full_days: 90
  estimates_zero_days: 180
  pt_full_days: 120
  pt_zero_days: 240
  reweight_missing: true
  data_coverage_penalty_max: 3

normalization:
  winsorize_p_low: 5
  winsorize_p_high: 95
  sector_blend: 0.30

vendors:
  use_finnhub: true
  use_yfinance: true
  use_fmp: true

progress:
  every: 100

fmp_harvest:
  daily_quota: 250
  ttl_days: 10
  ring_buffer: true
  disagreement_threshold_pct: 15
  merge_trimmed_mean: true
  failure_backoff_days: 30

paths:
  output_dir: output
  cache_dir: cache
  state_dir: state

debug:
  enabled: true
  log_file: output/debuglog.txt
  write_missing_summary_csv: true
  missing_summary_csv: output/missing_summary.csv
  top_missing_columns: 15
